package com.tamixa.application.port

import com.tamixa.domain.UsageTracking

/**
 * Server-side usage for plan limits. FREE: max stories/month; all plans: voice_generations for future limits.
 */
interface UsageTrackingPort {

    /** Get or create usage for parent + month (format yyyy-MM). */
    fun getOrCreate(parentId: Long, month: String): UsageTracking

    /** Increment stories_generated by 1; call after story is created. */
    fun incrementStories(parentId: Long, month: String)

    /** Increment voice_generations by 1. */
    fun incrementVoice(parentId: Long, month: String)
}

/** Extended usage metrics for revenue intelligence (story counts by plan). */
interface UsageMetricsPort {
    fun sumStoriesForFreePlan(month: String): Long
    fun sumStoriesForPaidPlan(month: String): Long
}
